In [1]:
import re
import pandas as pd
import numpy as np

In [40]:
df=pd.read_csv(r"C:\Users\Abinay Rachakonda\Desktop\Sentiment Analysis\reviews.csv")

In [43]:
df.head()

ProductId          UserId       ProfileName  HelpfulnessNumerator  \
0  B001E4KFG0  A3SGXH7AUHU8GW        delmartian                     1   
1  B00171APVA  A21BT40VZCCYT4     Carol A. Reed                     0   
2  B0019CW0HE  A2P6ACFZ8FTNVV  Melissa Benjamin                     0   
3  B006F2NYI2  A132DJVI37RB4X         Scottdrum                     2   
4  B000P41A28   A82WIMR4RSVLI        Emrose mom                     0   

   HelpfulnessDenominator  Score        Time                ReviewSummary  \
0                       1      5  1303862400        Good Quality Dog Food   
1                       0      5  1351209600             Healthy Dog Food   
2                       1      1  1331164800                          Bad   
3                       5      2  1332374400        Not hot, not habanero   
4                       1      4  1337472000   The best weve tried so far   

                                          ReviewText  
0  I have bought several of the Vitality canned d...  
1  This is a very healthy dog food. Good for thei...  
2  I fed this to my Golden Retriever and he hated...  
3  I have to admit, I was a sucker for the large ...  
4  We have a 7 week old... He had gas and constip...

In [44]:
df.columns

Index(['ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'ReviewSummary',
       'ReviewText'],
      dtype='object')

In [45]:
df.shape

(487679, 9)

In [46]:
df=df.sample(n=7000)

In [47]:
df.head()

ProductId          UserId                        ProfileName  \
157820  B001AHJ2FQ  A1LZJZIHUPLDV4  vegancompassion "anattanupassana"   
152148  B000E3VAO8  A136G8W1C0N53G            Lawrence Harris "tnreb"   
275470  B001E6IUMY  A308W7KL8KJDZC  Photography Buff "vintage photos"   
183852  B00024DB6Y  A3IND1N3J0XA7I                    Kenneth G. Wilk   
372319  B005JDCFCY   A5KVTBI8FA961        Houston Guy "Daniel Hughes"   

        HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
157820                     2                       3      5  1220486400   
152148                     0                       0      5  1331424000   
275470                     0                       0      5  1317168000   
183852                     0                       0      1  1325462400   
372319                     0                       0      5  1349827200   

                                         ReviewSummary  \
157820         Vegan Natural Kosher Gluten-Free Choice   
152148                                     gumbo pasta   
275470                                   Nature VAlley   
183852   Cal-free Thousand Island huge disappointment.   
372319                             Old Fashioned Taste   

                                               ReviewText  
157820  Vegan. Natural. Kosher. Has "Certified Gluten-...  
152148  This is good pasta.  I cannot find it in my ar...  
275470  My husband likes these bars with his coffee ea...  
183852  I was looking for no-fat salad dressings and s...  
372319  I have loved this candy since I was a child in...

In [48]:
df.shape

(7000, 9)

In [49]:
df['Score'].value_counts()

5    4589
4     950
1     598
3     495
2     368
Name: Score, dtype: int64

In [50]:
df[['HelpfulnessNumerator','HelpfulnessDenominator','Score','Time']]=df[['HelpfulnessNumerator','HelpfulnessDenominator','Score','Time']].astype('int64')

In [51]:
df.dtypes

ProductId                 object
UserId                    object
ProfileName               object
HelpfulnessNumerator       int64
HelpfulnessDenominator     int64
Score                      int64
Time                       int64
ReviewSummary             object
ReviewText                object
dtype: object

In [52]:
y=df['Score']
X=df[[ 'ReviewSummary',
       'ReviewText']]

In [59]:
from sklearn.model_selection import train_test_split
x_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [60]:
x_train.shape

(4900, 2)

In [61]:
x_train.head()

ReviewSummary  \
463119   Dog loved it, but dangerous   
308570               Absolute Heaven   
282576          the foods lucy loves   
390863     Too weak for my taste....   
43795                       Expired?   

                                               ReviewText  
463119  Our pup LOVED this bone. It's huge and meaty, ...  
308570  I am a chocolate fan, I love milk chocolate bu...  
282576  I started Lucy on Bench and Field Holistic as ...  
390863  I purchased this coffee for the first time bec...  
43795   These candies taste okay, and helped with morn...

In [62]:
y_test.shape

(2100,)

In [63]:
y_train.shape

(4900,)

In [64]:
import re
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [65]:
## initialise the inbuilt Stemmer
stemmer = PorterStemmer()

In [66]:
## We can also use Lemmatizer instead of Stemmer
lemmatizer = WordNetLemmatizer()

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

vocab = CountVectorizer()

X_train_bow = vocab.fit_transform(temp_df1['clean_text_lemma'],temp_df2['clean_text_lemma'])

In [67]:
def preprocess(raw_text, flag):
    # Removing special characters and digits
    sentence = re.sub("[^a-zA-Z]", " ", str(raw_text))
    
    # change sentence to lower case
    sentence = sentence.lower()

    # tokenize into words
    tokens = sentence.split()
    
    # remove stop words                
    clean_tokens = [t for t in tokens if not t in stopwords.words("english")]
    
    # Stemming/Lemmatization
    if(flag == 'stem'):
        clean_tokens = [stemmer.stem(word) for word in clean_tokens]
    else:
        clean_tokens = [lemmatizer.lemmatize(word) for word in clean_tokens]
    
    return pd.Series([" ".join(clean_tokens), len(clean_tokens)])

In [68]:
from tqdm import tqdm, tqdm_notebook

In [69]:
tqdm.pandas()

In [70]:
temp_df1 = x_train["ReviewSummary"].progress_apply(lambda x: preprocess(x, 'lemma'))



100%|██████████████████████████████████████████████████████████████████████████████████████████| 4900/4900 [00:19<00:00, 255.63it/s]


In [71]:
temp_df1

0  1
463119  dog loved dangerous  3
308570      absolute heaven  2
282576       food lucy love  3
390863           weak taste  2
43795               expired  1
...                     ... ..
40304            overpriced  1
158800                sweet  1
116743            impressed  1
25640      great herbal tea  3
32963            great chip  2

[4900 rows x 2 columns]

In [72]:
temp_df1.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df1.head()

clean_text_lemma  text_length_lemma
463119  dog loved dangerous                  3
308570      absolute heaven                  2
282576       food lucy love                  3
390863           weak taste                  2
43795               expired                  1

In [73]:
temp_df2 = x_train['ReviewText'].progress_apply(lambda x: preprocess(x, 'lemma'))


100%|███████████████████████████████████████████████████████████████████████████████████████████| 4900/4900 [04:12<00:00, 19.44it/s]


NameError: name 'temp_df_' is not defined

In [74]:
temp_df2.head()

0   1
463119  pup loved bone huge meaty took pretty hilariou...  52
308570  chocolate fan love milk chocolate love dark ch...  46
282576  started lucy bench field holistic puppy got di...  32
390863  purchased coffee first time sale tully house b...  44
43795   candy taste okay helped morning sickness tiny ...  25

In [75]:
temp_df2.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df1.head()

clean_text_lemma  text_length_lemma
463119  dog loved dangerous                  3
308570      absolute heaven                  2
282576       food lucy love                  3
390863           weak taste                  2
43795               expired                  1

In [77]:
X_train = pd.concat([x_train, temp_df1,temp_df2], axis=1)

X_train.head()

ReviewSummary  \
463119   Dog loved it, but dangerous   
308570               Absolute Heaven   
282576          the foods lucy loves   
390863     Too weak for my taste....   
43795                       Expired?   

                                               ReviewText  \
463119  Our pup LOVED this bone. It's huge and meaty, ...   
308570  I am a chocolate fan, I love milk chocolate bu...   
282576  I started Lucy on Bench and Field Holistic as ...   
390863  I purchased this coffee for the first time bec...   
43795   These candies taste okay, and helped with morn...   

           clean_text_lemma  text_length_lemma  \
463119  dog loved dangerous                  3   
308570      absolute heaven                  2   
282576       food lucy love                  3   
390863           weak taste                  2   
43795               expired                  1   

                                         clean_text_lemma  text_length_lemma  
463119  pup loved bone huge meaty took pretty hilariou...                 52  
308570  chocolate fan love milk chocolate love dark ch...                 46  
282576  started lucy bench field holistic puppy got di...                 32  
390863  purchased coffee first time sale tully house b...                 44  
43795   candy taste okay helped morning sickness tiny ...                 25

In [109]:
from sklearn.feature_extraction.text import TfidfVectorizer
vocab2 = TfidfVectorizer()
X_train_tfidf2 = vocab2.fit_transform(temp_df2['clean_text_lemma'])

In [110]:
X_train_tfidf2

<4900x12840 sparse matrix of type '<class 'numpy.float64'>'
	with 164374 stored elements in Compressed Sparse Row format>

In [81]:
print(X_train_tfidf2.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [83]:
temp_df3 = X_test['ReviewText'].progress_apply(lambda x: preprocess(x, 'lemma'))


100%|███████████████████████████████████████████████████████████████████████████████████████████| 2100/2100 [01:09<00:00, 30.42it/s]


In [84]:
temp_df3.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df3.head()

clean_text_lemma  text_length_lemma
440872  highly recommend water enjoy smartwater simila...                 31
123255  never resist trying new sweet angry bird fan p...                 54
168149  span class tiny length min br br span howdy br...                 94
250529  new sweet peppermint stride gum version item p...                 15
245757  big fan kind bar need healthy snack light meal...                 47

In [85]:
temp_df4 = X_test['ReviewSummary'].progress_apply(lambda x: preprocess(x, 'lemma'))

temp_df4.head()

100%|██████████████████████████████████████████████████████████████████████████████████████████| 2100/2100 [00:02<00:00, 706.90it/s]


0  1
440872     silky smooth water electrolyte  4
123255               fabulous fruit snack  3
168149                         basil leaf  2
250529  version original sweet peppermint  4
245757            excellent granola sweet  3

In [86]:
temp_df4.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df4.head()

clean_text_lemma  text_length_lemma
440872     silky smooth water electrolyte                  4
123255               fabulous fruit snack                  3
168149                         basil leaf                  2
250529  version original sweet peppermint                  4
245757            excellent granola sweet                  3

In [87]:
X_test = pd.concat([X_test, temp_df3,temp_df4], axis=1)

X_test.head()

ReviewSummary  \
440872               Silky smooth water with electrolytes   
123255                             Fabulous fruit snacks!   
168149                              NOT "with basil leaf"   
250529   this is the 2.0 version..not the original swe...   
245757                   Excellent granola, not too sweet   

                                               ReviewText  \
440872  I highly recommend this water to those that en...   
123255  I can never resist trying out new sweets and a...   
168149  <span class="tiny"> Length:: 0:40 Mins<br /><b...   
250529  this is the new sweet peppermint stride gum..v...   
245757  I'm a big fan of Kind bars when I need a healt...   

                                         clean_text_lemma  text_length_lemma  \
440872  highly recommend water enjoy smartwater simila...                 31   
123255  never resist trying new sweet angry bird fan p...                 54   
168149  span class tiny length min br br span howdy br...                 94   
250529  new sweet peppermint stride gum version item p...                 15   
245757  big fan kind bar need healthy snack light meal...                 47   

                         clean_text_lemma  text_length_lemma  
440872     silky smooth water electrolyte                  4  
123255               fabulous fruit snack                  3  
168149                         basil leaf                  2  
250529  version original sweet peppermint                  4  
245757            excellent granola sweet                  3

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer
X_test_tfidf2 = vocab2.transform(temp_df3['clean_text_lemma'])

In [96]:
temp_df3.shape

(2100, 2)

In [97]:
X_test.shape

(2100, 6)

In [114]:
X_test_tfidf2

<2100x12840 sparse matrix of type '<class 'numpy.float64'>'
	with 66842 stored elements in Compressed Sparse Row format>

# LogisticRegression

In [111]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_tfidf2, y_train)

LogisticRegression()

In [115]:
y_test_pred = classifier.predict(X_test_tfidf2)

In [116]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))

0.6852380952380952
              precision    recall  f1-score   support

           1       0.65      0.22      0.32       181
           2       0.67      0.04      0.08       100
           3       0.56      0.04      0.07       138
           4       0.48      0.09      0.15       306
           5       0.69      0.99      0.82      1375

    accuracy                           0.69      2100
   macro avg       0.61      0.27      0.29      2100
weighted avg       0.65      0.69      0.59      2100



In [201]:
y_test_pred = classifier.predict(X_train_tfidf2)

# RandomForestClassifier

In [122]:
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier()
classifier2.fit(X_train_tfidf2, y_train)

RandomForestClassifier()

In [123]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_test_pred))
print(classification_report(y_test,y_test_pred))

0.6852380952380952
              precision    recall  f1-score   support

           1       0.65      0.22      0.32       181
           2       0.67      0.04      0.08       100
           3       0.56      0.04      0.07       138
           4       0.48      0.09      0.15       306
           5       0.69      0.99      0.82      1375

    accuracy                           0.69      2100
   macro avg       0.61      0.27      0.29      2100
weighted avg       0.65      0.69      0.59      2100



In [124]:
from sklearn.tree import DecisionTreeClassifier
classifier3 = DecisionTreeClassifier()
classifier3.fit(X_train_tfidf2, y_train)

DecisionTreeClassifier()

In [125]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_test_pred))
print(classification_report(y_test,y_test_pred))

0.6852380952380952
              precision    recall  f1-score   support

           1       0.65      0.22      0.32       181
           2       0.67      0.04      0.08       100
           3       0.56      0.04      0.07       138
           4       0.48      0.09      0.15       306
           5       0.69      0.99      0.82      1375

    accuracy                           0.69      2100
   macro avg       0.61      0.27      0.29      2100
weighted avg       0.65      0.69      0.59      2100

